name: Building and Testing

on:
  push:
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies 
      run: |
        sudo apt-get update 
        sudo apt-get install -y --fix-missing cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev libglfw3-dev lcov
    
    - name: Configure
      run: |
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: |
        cmake --build ./build --config Debug
        
    - name: Setup xvfb and test for linux
      uses: GabrielBB/xvfb-action@v1
      with:
       run: ctest -C Debug --output-on-failure --verbose
       working-directory: ./build

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upload code coverage to coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools cpp-coveralls
        coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude "venv" --exclude "build/_deps"
