on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup cmake
      run: sudo apt-get install -y cmake
        
    - name:  Generate cmake files
      run: cmake -S . -B ./build
      
    - name: Build cmake 
      run: cmake --build ./build
