on:
  push:
    branches: [master]
  pull_request:
    branches: [master]


jobs:
  action_tests:
    runs-on: ${{ matrix.os }}
    name: Action Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cmake_ver: ['', '3.19.3', '3.15.1', '2.8']

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup cmake
      uses: ./
      id: setup
      with:
        cmake-version: ${{ matrix.cmake_ver }}
        
    - name: Build with cmake
      run: cmake -S . -B ./build
