name: Building and Testing

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies for Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update 
        sudo apt-get install -y --fix-missing cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl-dev libglfw3-dev
    
    - name: Install Dependencies for Windows
      if: contains(matrix.os, 'windows')
      run: |
        choco install cmake
        choco install glfw3
        
    - name: Install Dependencies for MacOS
      if: contains(matrix.os, 'macos')
      run: |
        brew install cmake
        brew install glfw
    
    - name: Configure
      run: |
        cmake -S . -B ./build

    - name: Build
      run: |
        cmake --build ./build 
        
    - name: Setup xvfb and test for linux
      if: contains(matrix.os, 'ubuntu')
      uses: GabrielBB/xvfb-action@v1
      with:
       run: ctest --verbose
       working-directory: ./build

    - name: Setup python
      uses: actions/setup-python@v2
      if: contains(matrix.os, 'ubuntu')
      with:
        python-version: 3.8

    - name: Upload code coverage to coveralls
      if: contains(matrix.os, 'ubuntu')
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools cpp-coveralls
        coveralls -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" --exclude "venv" --exclude "build/_deps"
